#!/usr/bin/env python3
"""
Amalgamates h5cpp headers into a single h5cpp.hpp file.

Usage:
    python3 scripts/amalgamate.py <input-dir> <output-file>

Example:
    python3 scripts/amalgamate.py h5cpp build/h5cpp.hpp
"""

import re
import sys
from pathlib import Path


def extract_preamble(text: str, guard_name: str):
    """
    Extracts lines before #ifndef GUARD from a file like 'core' or 'io'.
    Returns the preamble lines.
    """
    lines = text.splitlines()
    preamble = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#ifndef ") and guard_name in stripped:
            break
        preamble.append(line)
    return preamble


def process_file(filepath: Path) -> str:
    """Read a header file, strip #pragma once and internal h5cpp includes."""
    text = filepath.read_text(encoding="utf-8")
    lines = text.splitlines()
    out = []
    for line in lines:
        stripped = line.strip()
        # Skip #pragma once
        if stripped == "#pragma once":
            continue
        # Skip internal includes of other h5cpp headers or compat.hpp
        if re.match(r'#include\s+"(compat\.hpp|H5[^"]*\.hpp)"', stripped):
            continue
        out.append(line)
    return "\n".join(out)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    input_dir = Path(sys.argv[1])
    output_file = Path(sys.argv[2])

    core_file = input_dir / "core"
    if not core_file.exists():
        print(f"Error: {core_file} not found.")
        sys.exit(1)

    core_preamble = extract_preamble(
        core_file.read_text(encoding="utf-8"), "H5CPP_CORE_H"
    )

    # Manually curated order that satisfies all internal dependencies.
    # Derived from 'core' and 'io' entry points, with H5Iall.hpp moved
    # before H5Tmeta.hpp (which includes it) and prerequisites placed
    # before dependents.
    files = [
        # bootstrap -- macros and base types required by everything else
        "H5config.hpp",
        "compat.hpp",
        "H5Eall.hpp",
        "H5misc.hpp",
        "H5Iall.hpp",
        # core
        "H5meta.hpp",
        "H5Tmeta.hpp",
        "H5Mstl.hpp",
        "H5Sall.hpp",
        "H5Marma.hpp",
        "H5Mdlib.hpp",
        "H5Meigen.hpp",
        "H5Mblaze.hpp",
        "H5Mitpp.hpp",
        "H5Mublas.hpp",
        "H5Tall.hpp",
        "H5Zall.hpp",
        "H5Pall.hpp",
        "H5Zpipeline.hpp",
        "H5Zpipeline_basic.hpp",
        "H5Pdapl.hpp",
        "H5Ialgorithm.hpp",
        "H5capi.hpp",
        "H5cout.hpp",
        # io prerequisites not listed in core
        "H5Dgather.hpp",
        # io
        "H5Fcreate.hpp",
        "H5Fopen.hpp",
        "H5Dcreate.hpp",
        "H5Dopen.hpp",
        "H5Rall.hpp",
        "H5Dwrite.hpp",
        "H5Dread.hpp",
        "H5Dappend.hpp",
        "H5Acreate.hpp",
        "H5Aopen.hpp",
        "H5Awrite.hpp",
        "H5Aread.hpp",
        # extras (public API not pulled in by core/io)
        "H5Adelete.hpp",
    ]

    parts = []
    parts.append("/*")
    parts.append(" * Single-header amalgamated distribution of H5CPP")
    parts.append(" * Generated by scripts/amalgamate.py -- do not edit manually.")
    parts.append(" */")
    parts.append("")
    parts.append("#ifndef H5CPP_HPP")
    parts.append("#define H5CPP_HPP")
    parts.append("")

    if core_preamble:
        parts.append("/* --- core preamble --- */")
        parts.extend(core_preamble)
        parts.append("")

    count = 0
    for fname in files:
        filepath = input_dir / fname
        if not filepath.exists():
            print(f"Warning: {filepath} not found, skipping.")
            continue
        parts.append(f"/* --- {fname} --- */")
        parts.append(process_file(filepath))
        parts.append("")
        count += 1

    parts.append("#endif /* H5CPP_HPP */")
    parts.append("")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text("\n".join(parts), encoding="utf-8")
    print(f"Generated {output_file} ({count} files amalgamated)")


if __name__ == "__main__":
    main()
