# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget h5cpp libh5cpp-libdeflate libh5cpp-libdeflate-static libh5cpp-zstd libh5cpp-zstd-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target h5cpp
add_library(h5cpp INTERFACE IMPORTED)

set_target_properties(h5cpp PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H5CPP_HAS_LZ4=1"
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/steven/projects/vargalabs-workspace/worktrees/h5cpp/170-fix-include-correctness//home/steven/projects/vargalabs-workspace/worktrees/h5cpp/170-fix-include-correctness;/usr/local/include;/usr/include"
  INTERFACE_LINK_LIBRARIES "Threads::Threads;/usr/local/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so;ZLIB::ZLIB;libh5cpp-libdeflate;/usr/lib/x86_64-linux-gnu/liblz4.so;libh5cpp-zstd"
)

# Create imported target libh5cpp-libdeflate
add_library(libh5cpp-libdeflate INTERFACE IMPORTED)

set_target_properties(libh5cpp-libdeflate PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H5CPP_HAS_LIBDEFLATE=1"
  INTERFACE_LINK_LIBRARIES "libh5cpp-libdeflate-static"
)

# Create imported target libh5cpp-libdeflate-static
add_library(libh5cpp-libdeflate-static STATIC IMPORTED)

set_target_properties(libh5cpp-libdeflate-static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H5CPP_HAS_LIBDEFLATE=1"
  INTERFACE_COMPILE_FEATURES "c_std_99"
  INTERFACE_INCLUDE_DIRECTORIES "/home/steven/projects/vargalabs-workspace/worktrees/h5cpp/170-fix-include-correctness/thirdparty/libdeflate/v1.25.0"
)

# Create imported target libh5cpp-zstd
add_library(libh5cpp-zstd INTERFACE IMPORTED)

set_target_properties(libh5cpp-zstd PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H5CPP_HAS_ZSTD=1"
  INTERFACE_LINK_LIBRARIES "libh5cpp-zstd-static"
)

# Create imported target libh5cpp-zstd-static
add_library(libh5cpp-zstd-static STATIC IMPORTED)

set_target_properties(libh5cpp-zstd-static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "H5CPP_HAS_ZSTD=1"
  INTERFACE_COMPILE_FEATURES "c_std_99"
  INTERFACE_INCLUDE_DIRECTORIES "/home/steven/projects/vargalabs-workspace/worktrees/h5cpp/170-fix-include-correctness/thirdparty/zstd/v1.5.7/lib"
)

# Import target "libh5cpp-libdeflate-static" for configuration ""
set_property(TARGET libh5cpp-libdeflate-static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(libh5cpp-libdeflate-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/home/steven/projects/vargalabs-workspace/worktrees/h5cpp/170-fix-include-correctness/build-verify/thirdparty/libdeflate/liblibh5cpp-libdeflate-static.a"
  )

# Import target "libh5cpp-zstd-static" for configuration ""
set_property(TARGET libh5cpp-zstd-static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(libh5cpp-zstd-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "ASM;C"
  IMPORTED_LOCATION_NOCONFIG "/home/steven/projects/vargalabs-workspace/worktrees/h5cpp/170-fix-include-correctness/build-verify/thirdparty/zstd/liblibh5cpp-zstd-static.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
